name: React Native SDK Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run package install
        run: yarn
      - name: Run code format
        run: yarn run format
      - name: Run code lint
        run: yarn run lint
